package:
  version: "{{ load_setup_py_data().version }}"
  name: 'molmod'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - "{{ compiler('c') }}"
    - cython >=0.24.1
    - setuptools
    - nose
    - future
  run:
    - python
    - numpy
    - nose
    - future

about:
  dev_url: https://github.com/molmod/molmod
  description: MolMod is a collection of molecular modelling tools for python.
  license: GNU General Public License v3 or later (GPLv3+)
  license_family: GPL3
  summary: MolMod is a collection of molecular modelling tools for python.
  home: http://molmod.github.io/molmod/
  license_file: LICENSE.txt
  doc_url: http://molmod.github.io/molmod/

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
